### ISSUE TITLE
Could not find database with ID error

### ISSUE THREAD

**Issue by aglalit** [EgorDm/notionsci#4]
Can't sync, get an error: notion_client.errors.APIResponseError: Could not find database with ID: XXX
Double-checked everything, but it still doesn't work.

**Comment by EgorDm** [comment]
Hey,

Just to be sure. The masked id is the correct one right?
Also did you explicitly share the page the database is on with the API integration?
(See https://www.notion.so/Add-and-manage-integrations-with-the-API-910ac902372042bc9da38d48171269cd "Add integrations to pages" part)

**Comment by aglalit** [comment]
Shared it explicitly and now it works, thanks! Sorry for the unnecessary ticket.
