### ISSUE TITLE
notion_client.errors.APIResponseError: Could not find page with ID

### ISSUE THREAD

**Issue by Themistes** [EgorDm/notionsci#9]
Double checked api tokens in the configure file and explicitly shared the library database with integration, but still get this error message. 

Btw just want to make sure that the "notionsci sync zotero collections" command should follow the url of the "collections" database page instead of the url of the library page or the references page?

**Comment by egordm** [comment]
Docs are fixed. 
I will close the issue. If it persists feel free to reopen it.
